const express=require('express');
const { infoController, authCheckController, userController} = require('../../controllers');
const {userMiddleware}=require('../../middlewares');
const userRoutes=require('./user-routes');
const router=express.Router();
router.use('/user',userRoutes);
router.get('/info',infoController.info);
router.get('/admin',userMiddleware.setRole('admin'),userMiddleware.checkAuth,userMiddleware.hasRoleAccess,authCheckController.isAdmin);
router.get('/company',userMiddleware.setRole('xyz_tech'),userMiddleware.checkAuth,userMiddleware.hasRoleAccess,authCheckController.isAdmin);
module.exports=router;
